# This workflow triggers Check-in develop in sadist-ci repo

name: Check-in develop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Trigger sadist-ci's reusable workflow
    uses: ilyaukin/sadist-ci/.github/workflows/ci-develop.yml@develop
    secrets: inherit